### ISSUE TITLE
Feature: User can create a profile

### ISSUE THREAD

**Issue by kyledavid8** [kyledavid8/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a profile

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user signs-up they input a username and password, they will use their username and password to sing-in the next time they visit. When the user sends a message their username will be used as to who sent it.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/62397796/128797695-428348cd-18c3-4090-bc26-b42868e577e1.png)
![image](https://user-images.githubusercontent.com/62397796/128797721-3379ab96-cd54-4585-b25b-e6044ec6f9f4.png)
![image](https://user-images.githubusercontent.com/62397796/128798909-21ad0de6-8c08-411a-88dc-b25944172872.png)

## ✅ Task List

- [ ] create the layout of the form
- [ ] create a form
- [ ] the form should submit, when submitted should insert into your database
- [ ] make sure before the users info is inserted that there is no username that is the same and the passwords the user inputed match
- [ ] create a form for a already exisitng user to sign into by accessing the database and verifying.

### 🐘 Database

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client
- [ ] Add POST /api/sign-in - Endpoint to log a user in by generating a token
- [ ] Add POST /api/sign-up - Endpoint to create an account

### ⚡ Client

- [ ] Create a component to handle the form.
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
