### ISSUE TITLE
Feature: User can navigate and see created chat rooms in the “home page”

### ISSUE THREAD

**Issue by kyledavid8** [kyledavid8/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can navigate and see created chat rooms in the “home page”

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon sign-up or sign-in the user will see the "hoe page", where the main content is their created rooms while the top right says "log." the name of the app and the left a side-bar button which when clicked opens a side bar which has all the navigational needs for the user to access.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/62397796/128804374-b1a7963c-024c-4368-8f0e-420af305e58f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] create the layout of the home page
- [ ] when the user clicks for the side-bar, it opens with transition props.
- [ ] The side-bar should have content in it(not yet accessible, except the about page and account page)
- [ ] make sure when the user clicks out of the side-bar or clicks the back arrow it goes away WITH transition props
- [ ] build the account/about page
- [ ] When the user goes back from the about/account page they return to the homepage

### 🐘 Database

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client
- [ ] For the account page, use get to receive the users username to display

### ⚡ Client

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
